name: CI Docker Build

on:
  push:
    branches:
      - main

jobs:
  env:
    STEP1:"Lister les fichiers"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Lister les fichiers
        run: echo $STEP1

      - name: Build de l'image Docker
        run: echo   "$salut= {{vars.STEP2}}"
        
      - name: Lister les fichiers
        run: echo   "$salut= {{secret.janet}}"
        
