name: CI workflows
on:
  push:

jobs:
  docker:
    runs-on: self-hosted 
      #runs-on: ubuntu-latest 
    env:
      IMAGE_NAME: testcicd
      IMAGE_TAG: 1.1.0
      DOCKER_HUB_REGISTRY: docker.io/khadijaso

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Test Variables
        run: |
          echo "Variable MONVAR  ${{ vars.MONVAR }}"
          echo "Variable IMAGE_NAME $IMAGE_NAME"
          echo "Variable DOCKER_HUB_REGISTRY  $DOCKER_HUB_REGISTRY"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l'image Docker
        run: docker build -t $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Test de l'image Docker
        run: docker image ls $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Push image Docker
        run: docker push $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG